version: '3.8'

services:
  db:
    image: postgres:13.4-alpine
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_PASSWORD: password
    expose:
      - "5432"
    # volumes:
    #   - ./minnano_asobi/tmp/db:/var/lib/postgresql/data

  minnano_asobi:
    image: app_minnano_asobi
    build:
      context: ./minnano_asobi
      args:
        WORKDIR: app
        DOCKER_RAILS_ENV: ${DOCKER_RAILS_ENV}
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./minnano_asobi:/app
    depends_on:
      - db
#    ports:
#      - "3000:3000"

  nginx:
    image: nginx
    build: nginx
    ports:
      - "80:80"
    volumes_from:
      - minnano_asobi
    depends_on:
      - minnano_asobi