version: '3.8'

services:
  db:
    image: postgres:13.4-alpine
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_PASSWORD: password
    expose:
      - "5432"
    volumes:
      - ./minnano_asobi/tmp/db:/var/lib/postgresql/data

  chrome:
    image: selenium/standalone-chrome:latest
    # image: selenium/standalone-chrome-debug:latest
    ports:
      - 4444:4444
      # - 5900:5900

  minnano_asobi:
    image: app_minnano_asobi
    build:
      context: ./minnano_asobi
      args:
        WORKDIR: app
        DOCKER_RAILS_ENV: ${DOCKER_RAILS_ENV}
    environment:
      POSTGRES_PASSWORD: password
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
    command: bundle exec puma -e ${DOCKER_RAILS_ENV} -C config/puma.rb
    volumes:
      - ./minnano_asobi:/app
    depends_on:
      - db
      - chrome

  nginx:
    image: nginx
    build: nginx
    ports:
      - "80:80"
    volumes_from:
      - minnano_asobi
    depends_on:
      - minnano_asobi