name: check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: compose-run
        shell: bash
        env:
          DOCKER_RAILS_ENV: ${{ secrets.DOCKER_RAILS_ENV }}
        run: |
          free -m
          docker-compose up -d --build
          free -m
          docker-compose exec -T minnano_asobi sh github-actions/github-actions-process_rspec.sh