name: check-no-docker

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ruby:2.7.1
      env:
        RAIL_ENV: test

    services:
      db:
        image: postgres:13.4-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
      chrome:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      - uses: actions/checkout@v2
      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: ./minnano_asobi/vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Cache node packages
        uses: actions/cache@v1
        with:
          path: ./minnano_asobi/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: check folder
        run: ls
      - name: check pwd
        run: pwd
      - name: check bundle version
        run: bundle version
      - name: Execute check
        env:
          RAILS_ENV: test
          SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
        shell: bash
        working-directory: ./minnano_asobi
        run: |
          gem install bundler -v 2.2.19
          bundle config path vendor/bundle
          bundle _2.2.19_ install --jobs 4 --retry 3
          bundle exec rails db:setup
          bundle exec rspec