name: Minnano-asobi-ci

on:
  push:
    # branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: compose-run
        shell: bash
        env:
          DOCKER_RAILS_ENV: ${{ secrets.DOCKER_RAILS_ENV}}
        run: |
          docker-compose up -d